#Perform SonarCloud scan against Profile Designer API code
name: SonarCloud|API|Profile Designer - Scan
on:
  workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        #Github creates dynamically for each workflow run: 
        #https://docs.github.com/en/actions/security-guides/automatic-token-authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #in sonar.bat, this was the value assigned to login=token
        SONAR_TOKEN: ${{ secrets.SONAR_ACCESS_TOKEN }}
