# SonarCloud|API|Profile Designer - Scan - manually triggered

name: SonarCloud|API|Profile Designer - Scan

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./api
        args: >
          -Dsonar.organization=cesmii
          -Dsonar.projectKey=cesmii_ProfileDesigner
    env:
        #Github creates dynamically for each workflow run: 
        #https://docs.github.com/en/actions/security-guides/automatic-token-authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #in sonar.bat, this was the value assigned to login=token
        SONAR_TOKEN: ${{ secrets.SONAR_ACCESS_TOKEN }}      
